extent.reporter.spark.start=true
extent.reporter.spark.out=test-output/ExtentReport.html

extent.reporter.spark.config.document-title=Goibibo Automation Report
extent.reporter.spark.config.report-name=Goibibo BDD Test Results
extent.reporter.spark.config.theme=dark
extent.reporter.spark.config.encoding=UTF-8
